services:
  backend:
    build:
      context: ./backend
    container_name: chat_backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_PATH=./src
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - chat_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: chat_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - chat_network

networks:
  chat_network:
    name: chat_network
    driver: bridge

volumes:
  db_data:
