services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - chat_network

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chat_network

volumes:
  db_data:

networks:
  chat_network:
    driver: bridge
