services:

  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ./.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - chat_network

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - chat_network

  mysql:
    image: mysql:latest
    container_name: chat_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - chat_network

volumes:
  db_data:

networks:
  chat_network:
    driver: bridge
